##################################################
######## Thanks for Purchasing my Plugin! ########
# If you have any query's, message me on Spigot: #
# https://www.spigotmc.org/members/jet315.15295/ #
##################################################

#Should smelting be halted if the player moves? Set false if the player should be able to move around
CancelSmeltingOnMove: false
#Whether the Action Bar is enabled during the smelting process (May as well disable this if you have smelting set to instant)
EnableActionBar: true
#Should an inventory be used to smelt items? (They run the /smelt command,  an inventory opens, they put the items they want to smelt into that inventory)
#HIGHLY suggested, else all smeltable items in inventory will be smelted :/
EnableSmeltInventory: true
#Name of the smelt inventory,size and the confirm item ID, if enabled
NameOfSmeltInventory: '&7Smelting'
SizeOfSmeltInventory: 27
#You must put Material:data (So if you wanted this a coal for example, COAL:0)
ConfirmItemID: STAINED_GLASS_PANE:5
#Should permissions be used to check each smelting item? (If this is set to true, players will need permissions such as advancedsmelting.COAL_ORE to be able to smelt coal,etc)
IndividualSmeltingPermissions: false
#If a player does not have permission to smelt a particular item, should they get a the 'NoItemPermission' (Suggested if Inventory is enabled, false otherwise)
ShowInvalidItemPermissions: true
#The items that can be smelted - If you don't want an item smeltable, simply comment it out using #'s
Items:
  PORK:
    #Data is the number that comes after an item, so a SPONGE with a data value of 1 is a Wet Sponge (SPONGE:1).
    Data: 0
    #The amount of XP to give, when smelted
    ExpToGive: 0.3
    #The amount of time, in milliseconds, to smelt the item (Must be integer and CANNOT be more than the ActionBarTickRate*20)
    TimeToSmelt: 40
    #The cost of coal needed to smelt this item
    CostOfCoalToSmelt: 0.2
    #The cost of money needed to smelt this item
    CostOfMoneyToSmelt: 5
  RAW_BEEF:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 80
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  RAW_CHICKEN:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 80
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  RAW_FISH:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  MUTTON:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 80
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  RABBIT:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 80
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  POTATO_ITEM:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  IRON_ORE:
    Data: 0
    ExpToGive: 0.5
    TimeToSmelt: 90
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  GOLD_ORE:
    Data: 0
    ExpToGive: 0.6
    TimeToSmelt: 90
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  SAND:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 60
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 4
  COBBLESTONE:
    Data: 0
    ExpToGive: 0.1
    TimeToSmelt: 30
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  CLAY_BALL:
    Data: 0
    ExpToGive: 0.3
    TimeToSmelt: 50
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 4
  NETHERRACK:
    Data: 0
    ExpToGive: 0.5
    TimeToSmelt: 120
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 6
  CLAY:
    Data: 0
    ExpToGive: 0.2
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  SMOOTH_BRICK:
    Data: 0
    ExpToGive: 0.2
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  DIAMOND_ORE:
    Data: 0
    ExpToGive: 0.8
    TimeToSmelt: 140
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 6
  LAPIS_ORE:
    Data: 0
    ExpToGive: 0.2
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  REDSTONE_ORE:
    Data: 0
    ExpToGive: 0.2
    TimeToSmelt: 60
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 4
  COAL_ORE:
    Data: 0
    ExpToGive: 0.5
    TimeToSmelt: 60
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 4
  EMERALD_ORE:
    Data: 0
    ExpToGive: 0.9
    TimeToSmelt: 140
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 6
  QUARTZ_ORE:
    Data: 0
    ExpToGive: 0.2
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 3
  LOG:
    Data: 0
    ExpToGive: 0.1
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  LOG_2:
    Data: 0
    ExpToGive: 0.1
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 2
  CACTUS:
    Data: 0
    ExpToGive: 0.5
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 4
  SPONGE:
    Data: 1
    ExpToGive: 0.2
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 6
  CHORUS_FRUIT:
    Data: 0
    ExpToGive: 0.4
    TimeToSmelt: 40
    CostOfCoalToSmelt: 0.2
    CostOfMoneyToSmelt: 5